<?php

namespace Database\Seeders;
use App\Models\Country;

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Country::truncate();

        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Aland', 'code' => 'AX'],
            ['name' => 'Albanie', 'code' => 'AL'],
            ['name' => 'Algerie', 'code' => 'DZ'],
            ['name' => 'Samoa Américaines', 'code' => 'AS'],
            ['name' => 'Andorre', 'code' => 'AD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Anguille', 'code' => 'AI'],
            ['name' => 'Antarctique', 'code' => 'AQ'],
            ['name' => 'Antigua-et-Barbuda', 'code' => 'AG'],
            ['name' => 'Argentine', 'code' => 'AR'],
            ['name' => 'Armenie', 'code' => 'AM'],
            ['name' => 'Aruba', 'code' => 'AW'],
            ['name' => 'Australie', 'code' => 'AU'],
            ['name' => 'Austriche', 'code' => 'AT'],
            ['name' => 'Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Bahamas', 'code' => 'BS'],
            ['name' => 'Bahreïn', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Barbade', 'code' => 'BB'],
            ['name' => 'Biélorussie', 'code' => 'BY'],
            ['name' => 'Belgique', 'code' => 'BE'],
            ['name' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Bénin', 'code' => 'BJ'],
            ['name' => 'Bermudes', 'code' => 'BM'],
            ['name' => 'Bhoutan', 'code' => 'BT'],
            ['name' => 'Bolivie', 'code' => 'BO'],
            ['name' => 'Bonaire, Saint-Eustache et Saba', 'code' => 'BQ'],
            ['name' => 'Bosnie-Herzégovine', 'code' => 'BA'],
            ['name' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Île Bouvet', 'code' => 'BV'],
            ['name' => 'Brésil', 'code' => 'BR'],
            ['name' => 'Territoire Britannique de l\'Océan Indien', 'code' => 'IO'],
            ['name' => 'Brunei', 'code' => 'BN'],
            ['name' => 'Bulgarie', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Cambodge', 'code' => 'KH'],
            ['name' => 'Cameroun', 'code' => 'CM'],
            ['name' => 'Canada', 'code' => 'CA'],
            ['name' => 'Cap-Vert', 'code' => 'CV'],
            ['name' => 'Îles Caïmans', 'code' => 'KY'],
            ['name' => 'République centrafricaine', 'code' => 'CF'],
            ['name' => 'Tchad', 'code' => 'TD'],
            ['name' => 'Chili', 'code' => 'CL'],
            ['name' => 'Chine', 'code' => 'CH'],
            ['name' => 'Christmas Island', 'code' => 'CX'],
            ['name' => 'Îles Cocos', 'code' => 'CC'],
            ['name' => 'Colombie', 'code' => 'CO'],
            ['name' => 'Comoros', 'code' => 'KM'],
            ['name' => 'Congo', 'code' => 'CG'],
            ['name' => 'République Démocratique Congo', 'code' => 'CD'],
            ['name' => 'Îles Cook', 'code' => 'CK'],
            ['name' => 'Costa Rica', 'code' => 'CR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI'],
            ['name' => 'Croatie', 'code' => 'HR'],
            ['name' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Curaçao', 'code' => 'CW'],
            ['name' => 'Chypre', 'code' => 'CY'],
            ['name' => 'République tchèque', 'code' => 'CZ'],
            ['name' => 'Danemark', 'code' => 'DK'],
            ['name' => 'Djibouti', 'code' => 'DJ'],
            ['name' => 'Dominique', 'code' => 'DM'],
            ['name' => 'République Dominicaine', 'code' => 'DO'],
            ['name' => 'Equateur', 'code' => 'EC'],
            ['name' => 'Egypte', 'code' => 'EG'],
            ['name' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Guinée équatoriale', 'code' => 'GQ'],
            ['name' => 'Érythrée', 'code' => 'ER'],
            ['name' => 'Estonie', 'code' => 'EE'],
            ['name' => 'Ethiopie', 'code' => 'ET'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK'],
            ['name' => 'Îles Féroé', 'code' => 'FO'],
            ['name' => 'Fidji', 'code' => 'FJ'],
            ['name' => 'Finlande', 'code' => 'FI'],
            ['name' => 'France', 'code' => 'FR'],
            ['name' => 'Guyane', 'code' => 'GF'],
            ['name' => 'Polynésie française', 'code' => 'PF'],
            ['name' => 'Terres Australes Françaises', 'code' => 'TF'],
            ['name' => 'Gabon', 'code' => 'GA'],
            ['name' => 'Gambie', 'code' => 'GM'],
            ['name' => 'Géorgie', 'code' => 'GE'],
            ['name' => 'Allemagne', 'code' => 'DE'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Gibraltar', 'code' => 'GI'],
            ['name' => 'Grèce', 'code' => 'GR'],
            ['name' => 'Groenland', 'code' => 'GL'],
            ['name' => 'Grenade', 'code' => 'GD'],
            ['name' => 'Guadeloupe', 'code' => 'GP'],
            ['name' => 'Guam', 'code' => 'GU'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guernesey', 'code' => 'GG'],
            ['name' => 'Guinée', 'code' => 'GN'],
            ['name' => 'Guinée-Bissau', 'code' => 'GW'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Île Heard et Îles McDonald Mcdonald', 'code' => 'HM'],
            ['name' => 'Vatican', 'code' => 'VA'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Hong Kong', 'code' => 'HK'],
            ['name' => 'Hongrie', 'code' => 'HU'],
            ['name' => 'Island', 'code' => 'IS'],
            ['name' => 'Inde', 'code' => 'IN'],
            ['name' => 'Indonésie', 'code' => 'ID'],
            ['name' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Irland', 'code' => 'IE'],
            ['name' => 'Isle of Man', 'code' => 'IM'],
            ['name' => 'Israël', 'code' => 'IL'],
            ['name' => 'Italie', 'code' => 'IT'],
            ['name' => 'Jamaïque', 'code' => 'JM'],
            ['name' => 'Japon', 'code' => 'JP'],
            ['name' => 'Jersey', 'code' => 'JE'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Kiribati', 'code' => 'KI'],
            ['name' => 'Corée du Sud', 'code' => 'CS'],
            ['name' => 'Corée du Nord', 'code' => 'CN'],
            ['name' => 'Koweït', 'code' => 'KW'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA'],
            ['name' => 'Latvia', 'code' => 'LV'],
            ['name' => 'Lebanon', 'code' => 'LB'],
            ['name' => 'Lesotho', 'code' => 'LS'],
            ['name' => 'Liberia', 'code' => 'LR'],
            ['name' => 'Libye', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'code' => 'LI'],
            ['name' => 'Lithuanie', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Macao', 'code' => 'MO'],
            ['name' => 'Macedoine', 'code' => 'MK'],
            ['name' => 'Madagascar', 'code' => 'MG'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Malaysie', 'code' => 'MY'],
            ['name' => 'Maldives', 'code' => 'MV'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Malte', 'code' => 'MT'],
            ['name' => 'Marshall Islands', 'code' => 'MH'],
            ['name' => 'Martinique', 'code' => 'MQ'],
            ['name' => 'Mauritanie', 'code' => 'MR'],
            ['name' => 'Mauritius', 'code' => 'MU'],
            ['name' => 'Mayotte', 'code' => 'YT'],
            ['name' => 'Mexique', 'code' => 'MX'],
            ['name' => 'Micronésie', 'code' => 'FM'],
            ['name' => 'Moldavie', 'code' => 'MD'],
            ['name' => 'Monaco', 'code' => 'MC'],
            ['name' => 'Mongolie', 'code' => 'MN'],
            ['name' => 'Montenegro', 'code' => 'ME'],
            ['name' => 'Montserrat', 'code' => 'MS'],
            ['name' => 'Maroc', 'code' => 'MA'],
            ['name' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Myanmar', 'code' => 'MM'],
            ['name' => 'Namibie', 'code' => 'NA'],
            ['name' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Pays-bas', 'code' => 'NL'],
            ['name' => 'Nouvelle Calédonie', 'code' => 'NC'],
            ['name' => 'Nouvelle Zélande', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'code' => 'NI'],
            ['name' => 'Niger', 'code' => 'NE'],
            ['name' => 'Nigéria', 'code' => 'NG'],
            ['name' => 'Niue', 'code' => 'NU'],
            ['name' => 'Île Norfolk', 'code' => 'NF'],
            ['name' => 'Îles Mariannes du Nord', 'code' => 'MP'],
            ['name' => 'Norvège', 'code' => 'NO'],
            ['name' => 'Oman', 'code' => 'OM'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Palau', 'code' => 'PW'],
            ['name' => 'Palestine, State of', 'code' => 'PS'],
            ['name' => 'Panama', 'code' => 'PA'],
            ['name' => 'Papouasie Nouvelle Guinée', 'code' => 'PG'],
            ['name' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Pérou', 'code' => 'PE'],
            ['name' => 'Philippines', 'code' => 'PH'],
            ['name' => 'Pitcairn', 'code' => 'PN'],
            ['name' => 'Pologne', 'code' => 'PL'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Puerto Rico', 'code' => 'PR'],
            ['name' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Réunion', 'code' => 'RE'],
            ['name' => 'Roumanie', 'code' => 'RO'],
            ['name' => 'Russie', 'code' => 'RU'],
            ['name' => 'Rwanda', 'code' => 'RW'],
            ['name' => 'Saint Barthélemy', 'code' => 'BL'],
            ['name' => 'Sainte Hélène, Ascension et Tristan da Cunha', 'code' => 'SH'],
            ['name' => 'Saint Kitts et Nevis', 'code' => 'KN'],
            ['name' => 'Sainte Lucie', 'code' => 'LC'],
            ['name' => 'Saint Martin', 'code' => 'MF'],
            ['name' => 'Saint Pierre et Miquelon', 'code' => 'PM'],
            ['name' => 'Saint Vincent et les Grenadines', 'code' => 'VC'],
            ['name' => 'Samoa', 'code' => 'WS'],
            ['name' => 'Saint Marin', 'code' => 'SM'],
            ['name' => 'Sao Tomé-et-Principe', 'code' => 'ST'],
            ['name' => 'Arabie saoudite', 'code' => 'SA'],
            ['name' => 'Sénégal', 'code' => 'SN'],
            ['name' => 'Serbie', 'code' => 'RS'],
            ['name' => 'Seychelles', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singapour', 'code' => 'SG'],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX'],
            ['name' => 'Slovaquie', 'code' => 'SK'],
            ['name' => 'Slovénie', 'code' => 'SI'],
            ['name' => 'îles Salomon', 'code' => 'SB'],
            ['name' => 'Somalie', 'code' => 'SO'],
            ['name' => 'Afrique du Sud', 'code' => 'ZA'],
            ['name' => 'Géorgie du Sud et îles Sandwich du Sud', 'code' => 'GS'],
            ['name' => 'Soudan du Sud', 'code' => 'SS'],
            ['name' => 'Espagne', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Soudan', 'code' => 'SD'],
            ['name' => 'Suriname', 'code' => 'SR'],
            ['name' => 'Svalbard et Jan Mayen', 'code' => 'SJ'],
            ['name' => 'Swaziland', 'code' => 'SZ'],
            ['name' => 'Suède', 'code' => 'SE'],
            ['name' => 'Suisse', 'code' => 'SUI'],
            ['name' => 'Syrie', 'code' => 'SY'],
            ['name' => 'Taiwan', 'code' => 'TW'],
            ['name' => 'Tadjikistan', 'code' => 'TJ'],
            ['name' => 'Tanzanie', 'code' => 'TZ'],
            ['name' => 'Thaïlande', 'code' => 'TH'],
            ['name' => 'Timor-Leste', 'code' => 'TL'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Tokelau', 'code' => 'TK'],
            ['name' => 'Tonga', 'code' => 'TO'],
            ['name' => 'Trinité et Tobago', 'code' => 'TT'],
            ['name' => 'Tunisie', 'code' => 'TN'],
            ['name' => 'Turquie', 'code' => 'TR'],
            ['name' => 'Turkménistan', 'code' => 'TM'],
            ['name' => 'îles Turques et Caïques', 'code' => 'TC'],
            ['name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'Émirats arabes unis', 'code' => 'AE'],
            ['name' => 'Royaume-Uni', 'code' => 'GB'],
            ['name' => 'États-Unis', 'code' => 'US'],
            ['name' => 'Îles mineures éloignées des États-Unis', 'code' => 'UM'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Ouzbékistan', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'code' => 'VU'],
            ['name' => 'Vénézuela', 'code' => 'VE'],
            ['name' => 'Viet Nam', 'code' => 'VN'],
            ['name' => 'Les iles vierges, British', 'code' => 'VG'],
            ['name' => 'Les iles vierges, U.S.', 'code' => 'VI'],
            ['name' => 'Wallis et Futuna', 'code' => 'WF'],
            ['name' => 'Sahara occidental', 'code' => 'EH'],
            ['name' => 'Yémen', 'code' => 'YE'],
            ['name' => 'Zambie', 'code' => 'ZM'],
            ['name' => 'Zimbabwé', 'code' => 'ZW'],
        ];
          
        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}
